tempdir: /tmp
max_memory_MB: 100000
n_refs: 10
chromosome_list:
- chr21
ploidy: 2
ploidy_file: GRCh37
max_edit_distance: 10
max_read_len: 105
sensibility: 5
variant_caller:
- gatk
- samtools
workflow:
- pg
- baseline
