tempdir: /tmp
max_memory_MB: 64000
chromosome_list:
- chr21
max_edit_distance: 10
max_read_len: 105
ploidy: 2
ploidy_file: GRCh38
sensibility: 5
variant_caller:
- gatk
- samtools
workflow:
- pg
- baseline
